### ISSUE TITLE
Replace RaisedButton and FlatButton with ElevatedButton and TextButton

### ISSUE THREAD

**Issue by SteBry** [dibbs-team/dibbs#97]
RaisedButton, FlatButton have been made obselete
https://api.flutter.dev/flutter/material/RaisedButton-class.html

**Comment by SteBry** [comment]
We should also use the corresponding themes instead of ButtonTheme:

"ButtonTheme has been replaced by TextButtonTheme, ElevatedButtonTheme, and OutlinedButtonTheme. The original classes will be deprecated soon, please migrate code that uses them. There's a detailed migration guide for the new button and button theme classes in flutter.dev/go/material-button-migration-guide."
https://api.flutter.dev/flutter/material/ButtonThemeData-class.html

**Comment by Kal-Elx** [comment]
Design buttons according to theme at the same time.
